docs: add the shell-autocompletion support in optimus cli
odpf/optimus pull request #34
Opened 2021-07-10 18:10 UTC by scortier

### Description
1.  Automatically adds completion command for [shell completions](https://github.com/spf13/cobra/blob/master/shell_completions.md) for bash, zsh, fish and PowerShell. 
2. Users can configure the command auto creation:  
      1. disable the creation of the completion command
      2. disable completion descriptions
      3. disable the --no-descriptions flag for "always on" completion descriptions

### Preview
**Command to use : `./optimus [tab][tab]`**

<img width="1264" alt="Screenshot 2021-07-10 at 12 34 28 PM" src="https://user-images.githubusercontent.com/44753901/125155108-53e9f280-e17b-11eb-9270-8d99d71722f2.png">

### Related Issues 
Issue #32

2021-07-12 06:18 UTC, scortier commented
@kushsharma  please review the PR

2021-07-14 04:31 UTC, kushsharma requested changes

2021-07-14 04:31 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +## Additional Features :
Remove all of this, why would user care about this?

2021-07-14 04:31 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +The shell auto-completion feature in optimus CLI provide the relief you not to remember the specific command , you just need to type some initials of the command then complete command gets generated
People know what autocompletion is already, no need to explain

2021-07-14 04:31 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +Before moving towards setup one can check whether the functionality is enabled in it's Optimus binary by executing `optimus [tab][tab]` in the CLI. If it's working fine then you are good to go.
what to do mean here? what `functionality `

2021-07-14 04:31 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +The optimus completion script for Bash can be generated with `./optimus completion bash`. Sourcing this script in your shell enables optimus completion.
no need to specify `./` path of the optimus binary

2021-07-16 09:13 UTC, kushsharma requested changes

2021-07-16 09:13 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +- If you installed optimus with Homebrew (as explained here), then the optimus completion script should already be in /usr/local/etc/bash_completion.d/_optimus. In that case, you don't need to do any
link `as explained here`

2021-07-16 09:13 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +### 1. Bash auto-completion
No need for numeric list

2021-07-16 09:13 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +- If shell completion is not already enabled in your environment,you will need to enable it.You can execute the following once:
use proper text formatting like space after comma, space after `.`

2021-07-16 09:13 UTC, kushsharma commented on docs/guides/adding-shell-autocompletion.md
> +If you get an error like complete:13: command not found: compdef, then add the following to the beginning of your ~/.zshrc file:
put error in back ticks

2021-07-16 09:43 UTC, kushsharma commented on docs/docs/reference/shell-autocompletion.md
> +  $ ./optimus completion zsh > "${fpath[1]}/_optimus"
remove `./` from all examples

2021-07-19 09:03 UTC, merged