Revamp Config Overriding
odpf/optimus pull request #431
Opened 2022-07-05 03:40 UTC by deryrahman

2022-07-13 05:11 UTC, irainia requested changes
Also, if it's not update, maybe we can update the documentation

2022-07-13 05:16 UTC, irainia commented on cmd/backup/status.go
> +	cmd.Flags().StringVarP(&s.projectName, "project-name", "p", "", "project name of optimus managed repository")
we can ignore this one, as it does not use the project config

2022-07-13 05:17 UTC, irainia commented on cmd/backup/list.go
> +	cmd.Flags().StringVarP(&l.projectName, "project-name", "p", "", "project name of optimus managed repository")
we can also ignore this one, since this does not use project config

2022-07-15 03:49 UTC, deryrahman commented on cmd/backup/create.go
> +	cmd.Flags().StringVarP(&c.projectName, "project-name", "p", "", "project name of optimus managed repository")
Currently, we use project's config from config yaml, whether we provide flag `--project-name` or not. If, there's a case when user need to use corresponding project's config based on `project name`, then, the changes should be made

2022-07-18 02:59 UTC, irainia commented
There are some TODOs we need to address. However, since they are outside of the scope of this PR and the related issue, I created another issue (#441) to address it. The rest, LGTM.

2022-07-18 03:00 UTC, irainia approved these changes

2022-07-19 04:09 UTC, merged