add plugin manager
odpf/optimus pull request #434
Opened 2022-07-05 21:22 UTC by SaikumarChintada

New Features: 
* `optimus plugin install`
* `optimus serve --with-plugins`
* sample plugin config within optimus server config
```yaml
plugin:
  dir: ".plugins"
  artifacts:
    # refer : https://github.com/hashicorp/go-getter
    - ../transformers/dist/transformers_0.1.0_macos_arm64.tar.gz
    - ../transformers/dist/transformers_0.1.0_windows_x86_64.zip
    - https://github.com/odpf/optimus/releases/download/v0.2.5/optimus_0.2.5_linux_arm64.tar.gz
```

2022-07-17 15:22 UTC, sravankorumilli requested changes

2022-07-17 15:22 UTC, sravankorumilli commented on go.mod
> -	google.golang.org/grpc v1.46.0
why this change

2022-07-17 15:22 UTC, sravankorumilli commented on go.mod
> +	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.25.0
why this downgrage

2022-07-17 15:22 UTC, sravankorumilli commented on cmd/plugin/plugin_manager.go
> +func (p *PluginManager) Install(src, dst string) error {
just use variable arguments method instead of two methods

2022-07-17 15:22 UTC, sravankorumilli commented on cmd/plugin/install.go
> +func NewInstallCommand(serverConfig *config.ServerConfig) *cobra.Command {
as discussed we need to remove this command

2022-07-22 11:09 UTC, smarch-int commented on cmd/plugin/plugin.go
> +	serverConfig   *config.ServerConfig
I get your point, but when I add another command in plugin then I have to move it back to plugin level again.
I think its better to have all deps injected from parent command.

2022-07-26 15:53 UTC, sravankorumilli approved these changes

2022-07-31 15:24 UTC, sravankorumilli approved these changes

2022-07-31 15:24 UTC, merged